// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_EventExposure

AMF Event Exposure Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.5

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package eventexposure

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/amf/logger"
)

// Post /:$request.body#/subscription/eventNotifyUri
// Event Notification Delivery
func HTTPOnEventReportPost(c *gin.Context) {
	logger.CommLog.Warnln("Handle Post /:$request.body#/subscription/eventNotifyUri is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
