// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Namf_EventExposure

AMF Event Exposure Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.5

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package eventexposure

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/amf/logger"
	"github.com/omec-project/amf/producer"
	"github.com/omec-project/openapi"
	"github.com/omec-project/openapi/models"
	"github.com/omec-project/openapi/utils"
	"github.com/omec-project/util/httpwrapper"
)

// Delete /subscriptions/:subscriptionId
// Namf_EventExposure Unsubscribe service Operation
func HTTPDeleteSubscription(c *gin.Context) {
	logger.CommLog.Infoln("Handle Delete /subscriptions/:subscriptionId")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["subscriptionId"] = c.Param("subscriptionId")

	rsp := producer.HandleDeleteAMFEventSubscription(req)

	if rsp.Status == http.StatusOK {
		c.JSON(http.StatusOK, gin.H{})
	} else {
		responseBody, err := openapi.SetBody(rsp.Body, "application/json")
		if err != nil {
			logger.EeLog.Errorln(err)
			problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
			c.JSON(http.StatusInternalServerError, problemDetails)
		} else {
			c.Data(rsp.Status, "application/json", responseBody.Bytes())
		}
	}
}

// Patch /subscriptions/:subscriptionId
// Namf_EventExposure Subscribe Modify service Operation
func HTTPModifySubscription(c *gin.Context) {
	logger.CommLog.Infoln("Handle Patch /subscriptions/:subscriptionId")
	var modifySubscriptionRequest models.ModifySubscriptionRequest

	requestBody, err := c.GetRawData()
	if err != nil {
		logger.EeLog.Errorf("Get Request Body error: %+v", err)
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&modifySubscriptionRequest, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.EeLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, modifySubscriptionRequest)
	req.Params["subscriptionId"] = c.Param("subscriptionId")

	rsp := producer.HandleModifyAMFEventSubscription(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.EeLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}
