// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Location

AMF Location Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package location

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/amf/logger"
	"github.com/omec-project/amf/producer"
	"github.com/omec-project/openapi"
	"github.com/omec-project/openapi/models"
	"github.com/omec-project/openapi/utils"
	"github.com/omec-project/util/httpwrapper"
)

// Post /:ueContextId/cancel-pos-info
// Namf_Location CancelLocation service operation
func HTTPCancelLocation(c *gin.Context) {
	logger.CommLog.Warnln("Handle Post /:ueContextId/cancel-pos-info is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Post /:ueContextId/provide-loc-info
// Namf_Location ProvideLocationInfo service Operation
func HTTPProvideLocationInfo(c *gin.Context) {
	logger.CommLog.Infoln("Handle Post /:ueContextId/provide-loc-info")
	var requestLocInfo models.RequestLocInfo

	requestBody, err := c.GetRawData()
	if err != nil {
		logger.LocationLog.Errorf("Get Request Body error: %+v", err)
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&requestLocInfo, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.LocationLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, requestLocInfo)
	req.Params["ueContextId"] = c.Params.ByName("ueContextId")

	rsp := producer.HandleProvideLocationInfoRequest(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.CommLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Post /:ueContextId/provide-pos-info
// Namf_Location ProvidePositioningInfo service Operation
func HTTPProvidePositioningInfo(c *gin.Context) {
	logger.CommLog.Warnln("Handle Post /:ueContextId/provide-pos-info is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
