// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Location

AMF Location Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package location

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/amf/logger"
)

// Post /:$request.body#/locationNotificationUri
func HTTPOnUELocationNotificationPost(c *gin.Context) {
	detail := "Handle Post /:$request.body#/locationNotificationUri is not implemented"
	logger.CommLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
