// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Location

AMF Location Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package location

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/amf/logger"
	utilLogger "github.com/omec-project/util/logger"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method (e.g., GET, POST, etc.)
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

type routeParamAlias struct {
	canonical string
	original  string
}

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := utilLogger.NewGinWithZap(logger.GinLog)
	AddService(router)
	return router
}

// AddService add routes to existing gin engine.
func AddService(engine *gin.Engine) *gin.RouterGroup {
	group := engine.Group("/namf-loc/v1")
	for _, route := range getRoutes() {
		if shouldSkipRoute(route.Pattern) {
			continue
		}
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		ginPattern, aliases := canonicalizeRoutePattern(route.Pattern)
		handlerFunc := wrapRouteHandler(route.HandlerFunc, aliases)
		switch route.Method {
		case http.MethodGet:
			group.GET(ginPattern, handlerFunc)
		case http.MethodPost:
			group.POST(ginPattern, handlerFunc)
		case http.MethodPut:
			group.PUT(ginPattern, handlerFunc)
		case http.MethodPatch:
			group.PATCH(ginPattern, handlerFunc)
		case http.MethodDelete:
			group.DELETE(ginPattern, handlerFunc)
		}
	}

	return group
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

func shouldSkipRoute(pattern string) bool {
	return strings.Contains(pattern, "request.body#")
}

func canonicalizeRoutePattern(pattern string) (string, []routeParamAlias) {
	segments := strings.Split(pattern, "/")
	aliases := make([]routeParamAlias, 0)
	for index, segment := range segments {
		if len(segment) <= 1 || segment[0] != ':' {
			continue
		}
		original := segment[1:]
		canonical := fmt.Sprintf("param%d", index)
		segments[index] = ":" + canonical
		if original != canonical {
			aliases = append(aliases, routeParamAlias{canonical: canonical, original: original})
		}
	}
	return strings.Join(segments, "/"), aliases
}

func wrapRouteHandler(handler gin.HandlerFunc, aliases []routeParamAlias) gin.HandlerFunc {
	if len(aliases) == 0 {
		return handler
	}

	return func(c *gin.Context) {
		for _, alias := range aliases {
			value := c.Param(alias.canonical)
			if value == "" {
				continue
			}
			c.Params = append(c.Params, gin.Param{Key: alias.original, Value: value})
		}
		handler(c)
	}
}

func getRoutes() []Route {
	return []Route{
		{
			"CancelLocation",
			http.MethodPost,
			"/:ueContextId/cancel-pos-info",
			HTTPCancelLocation,
		},
		{
			"ProvideLocationInfo",
			http.MethodPost,
			"/:ueContextId/provide-loc-info",
			HTTPProvideLocationInfo,
		},
		{
			"ProvidePositioningInfo",
			http.MethodPost,
			"/:ueContextId/provide-pos-info",
			HTTPProvidePositioningInfo,
		},
		{
			"OnUELocationNotificationPost",
			http.MethodPost,
			"/:$request.body#/locationNotificationUri",
			HTTPOnUELocationNotificationPost,
		},
	}
}
