// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package communication

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/amf/logger"
)

// Post /:$request.body#/n1n2FailureTxfNotifURI
// Namf_Communication N1N2Transfer Failure Notification service Operation
func HTTPN1N2TransferFailureNotification(c *gin.Context) {
	logger.CommLog.Warnln("Handle Post /:$request.body#/n1n2FailureTxfNotifURI is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
