// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package communication

import (
	"bytes"
	"fmt"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/amf/logger"
	"github.com/omec-project/amf/producer"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/util/httpwrapper"
)

var (
	applicationJson  string = "application/json"
	multipartRelated string = "multipart/related"
)

// Post /ue-contexts/:ueContextId/cancel-relocate
// Namf_Communication CancelRelocateUEContext service Operation
func HTTPCancelRelocateUEContext(c *gin.Context) {
	detail := "Handle Post /ue-contexts/:ueContextId/cancel-relocate is not implemented"
	logger.CommLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Put /ue-contexts/:ueContextId
// Namf_Communication CreateUEContext service Operation
func HTTPCreateUEContext(c *gin.Context) {
	logger.CommLog.Infoln("Handle Put /ue-contexts/:ueContextId")
	var createUeContextRequest models.CreateUEContextRequest
	createUeContextRequest.JsonData = models.NewUeContextCreateDataWithDefaults()

	requestBody, err := c.GetRawData()
	if err != nil {
		logger.CommLog.Errorf("Get Request Body error: %+v", err)
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	contentType := c.GetHeader("Content-Type")
	s := strings.Split(contentType, ";")
	switch s[0] {
	case applicationJson:
		err = openapi.Decode(createUeContextRequest.JsonData, requestBody, contentType)
	case multipartRelated:
		err = openapi.Decode(&createUeContextRequest, requestBody, contentType)
	default:
		err = fmt.Errorf("wrong content type")
	}

	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.CommLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, createUeContextRequest)
	req.Params["ueContextId"] = c.Params.ByName("ueContextId")
	rsp := producer.HandleCreateUEContextRequest(req)

	if rsp.Status == http.StatusCreated {
		responseBody := new(bytes.Buffer)
		contentType, err := openapi.MultipartEncode(rsp.Body, responseBody)
		if err != nil {
			logger.CommLog.Errorln(err)
			problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
			c.JSON(http.StatusInternalServerError, problemDetails)
		} else {
			c.Data(rsp.Status, contentType, responseBody.Bytes())
		}
	} else {
		responseBody, err := openapi.SetBody(rsp.Body, "application/json")
		if err != nil {
			logger.CommLog.Errorln(err)
			problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
			c.JSON(http.StatusInternalServerError, problemDetails)
		} else {
			c.Data(rsp.Status, "application/json", responseBody.Bytes())
		}
	}
}

// Post /ue-contexts/:ueContextId/assign-ebi
// Namf_Communication EBI Assignment service Operation
func HTTPEBIAssignment(c *gin.Context) {
	logger.CommLog.Infoln("Handle Post /ue-contexts/:ueContextId/assign-ebi")
	var assignEbiData models.AssignEbiData

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.CommLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&assignEbiData, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.CommLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, assignEbiData)
	req.Params["ueContextId"] = c.Params.ByName("ueContextId")
	rsp := producer.HandleAssignEbiDataRequest(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.CommLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Post /ue-contexts/:ueContextId/transfer-update
// Namf_Communication RegistrationStatusUpdate service Operation
func HTTPRegistrationStatusUpdate(c *gin.Context) {
	logger.CommLog.Infoln("Handle Post /ue-contexts/:ueContextId/transfer-update")
	var ueRegStatusUpdateReqData models.UeRegStatusUpdateReqData

	requestBody, err := c.GetRawData()
	if err != nil {
		logger.CommLog.Errorf("Get Request Body error: %+v", err)
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&ueRegStatusUpdateReqData, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.CommLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, ueRegStatusUpdateReqData)
	req.Params["ueContextId"] = c.Params.ByName("ueContextId")
	rsp := producer.HandleRegistrationStatusUpdateRequest(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.CommLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Post /ue-contexts/:ueContextId/release
// Namf_Communication ReleaseUEContext service Operation
func HTTPReleaseUEContext(c *gin.Context) {
	logger.CommLog.Infoln("Handle Post /ue-contexts/:ueContextId/release")
	var ueContextRelease models.UEContextRelease

	requestBody, err := c.GetRawData()
	if err != nil {
		logger.CommLog.Errorf("Get Request Body error: %+v", err)
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&ueContextRelease, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.CommLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, ueContextRelease)
	req.Params["ueContextId"] = c.Params.ByName("ueContextId")
	rsp := producer.HandleReleaseUEContextRequest(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.CommLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Post /ue-contexts/:ueContextId/relocate
// Namf_Communication RelocateUEContext service Operation
func HTTPRelocateUEContext(c *gin.Context) {
	detail := "Handle Post /ue-contexts/:ueContextId/relocate is not implemented"
	logger.CommLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Post /ue-contexts/:ueContextId/transfer
// Namf_Communication UEContextTransfer service Operation
func HTTPUEContextTransfer(c *gin.Context) {
	logger.CommLog.Infoln("Handle Post /ue-contexts/:ueContextId/transfer")
	var ueContextTransferRequest models.UEContextTransferRequest
	ueContextTransferRequest.JsonData = models.NewUeContextTransferReqDataWithDefaults()

	requestBody, err := c.GetRawData()
	if err != nil {
		logger.CommLog.Errorf("Get Request Body error: %+v", err)
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	contentType := c.GetHeader("Content-Type")
	s := strings.Split(contentType, ";")
	switch s[0] {
	case applicationJson:
		err = openapi.Decode(ueContextTransferRequest.JsonData, requestBody, contentType)
	case multipartRelated:
		err = openapi.Decode(&ueContextTransferRequest, requestBody, contentType)
	}

	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.CommLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, ueContextTransferRequest)
	req.Params["ueContextId"] = c.Params.ByName("ueContextId")
	rsp := producer.HandleUEContextTransferRequest(req)

	if rsp.Status == http.StatusOK {
		responseBody := new(bytes.Buffer)
		contentType, err := openapi.MultipartEncode(rsp.Body, responseBody)
		if err != nil {
			logger.CommLog.Errorln(err)
			problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
			c.JSON(http.StatusInternalServerError, problemDetails)
		} else {
			c.Data(rsp.Status, contentType, responseBody.Bytes())
		}
	} else {
		responseBody, err := openapi.SetBody(rsp.Body, "application/json")
		if err != nil {
			logger.CommLog.Errorln(err)
			problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
			c.JSON(http.StatusInternalServerError, problemDetails)
		} else {
			c.Data(rsp.Status, "application/json", responseBody.Bytes())
		}
	}
}
