// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package communication

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/amf/logger"
)

// Delete /non-ue-n2-messages/subscriptions/:n2NotifySubscriptionId
// Namf_Communication Non UE N2 Info UnSubscribe service Operation
func HTTPNonUeN2InfoUnSubscribe(c *gin.Context) {
	detail := "Handle Delete /non-ue-n2-messages/subscriptions/:n2NotifySubscriptionId is not implemented"
	logger.CommLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
