// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package communication

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/amf/logger"
	"github.com/omec-project/openapi/v2/utils"
	utilLogger "github.com/omec-project/util/logger"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method (e.g., GET, POST, etc.)
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

type routeParamAlias struct {
	canonical string
	original  string
}

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := utilLogger.NewGinWithZap(logger.GinLog)
	AddService(router)
	return router
}

// AddService adds routes to an existing gin engine.
func AddService(engine *gin.Engine) *gin.RouterGroup {
	group := engine.Group("/namf-comm/v1")
	for _, route := range getRoutes() {
		if shouldSkipRoute(route.Pattern) {
			continue
		}
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		ginPattern, aliases := canonicalizeRoutePattern(route.Pattern)
		handlerFunc := wrapRouteHandler(route.HandlerFunc, aliases)
		switch route.Method {
		case http.MethodGet:
			group.GET(ginPattern, handlerFunc)
		case http.MethodOptions:
			group.OPTIONS(ginPattern, handlerFunc)
		case http.MethodPost:
			group.POST(ginPattern, handlerFunc)
		case http.MethodPut:
			group.PUT(ginPattern, handlerFunc)
		case http.MethodPatch:
			group.PATCH(ginPattern, handlerFunc)
		case http.MethodDelete:
			group.DELETE(ginPattern, handlerFunc)
		}
	}

	return group
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	writeNotImplementedProblem(c, "This API route is not implemented")
}

func writeNotImplementedProblem(c *gin.Context, detail string) {
	problemDetails := utils.ProblemDetailsNotImplemented(detail)
	c.JSON(http.StatusNotImplemented, problemDetails)
}

func shouldSkipRoute(pattern string) bool {
	return strings.Contains(pattern, "request.body#")
}

func canonicalizeRoutePattern(pattern string) (string, []routeParamAlias) {
	segments := strings.Split(pattern, "/")
	aliases := make([]routeParamAlias, 0)
	for index, segment := range segments {
		if len(segment) <= 1 || segment[0] != ':' {
			continue
		}
		original := segment[1:]
		canonical := fmt.Sprintf("param%d", index)
		segments[index] = ":" + canonical
		if original != canonical {
			aliases = append(aliases, routeParamAlias{canonical: canonical, original: original})
		}
	}
	return strings.Join(segments, "/"), aliases
}

func wrapRouteHandler(handler gin.HandlerFunc, aliases []routeParamAlias) gin.HandlerFunc {
	if len(aliases) == 0 {
		return handler
	}

	return func(c *gin.Context) {
		for _, alias := range aliases {
			value := c.Param(alias.canonical)
			if value == "" {
				continue
			}
			c.Params = append(c.Params, gin.Param{Key: alias.original, Value: value})
		}
		handler(c)
	}
}

func getRoutes() []Route {
	return []Route{
		{
			"AMFStatusChangeSubscribeModify",
			http.MethodPut,
			"/subscriptions/:subscriptionId",
			HTTPAMFStatusChangeSubscribeModify,
		},
		{
			"AMFStatusChangeUnSubscribe",
			http.MethodDelete,
			"/subscriptions/:subscriptionId",
			HTTPAMFStatusChangeUnSubscribe,
		},
		{
			"CancelRelocateUEContext",
			http.MethodPost,
			"/ue-contexts/:ueContextId/cancel-relocate",
			HTTPCancelRelocateUEContext,
		},
		{
			"CreateUEContext",
			http.MethodPut,
			"/ue-contexts/:ueContextId",
			HTTPCreateUEContext,
		},
		{
			"EBIAssignment",
			http.MethodPost,
			"/ue-contexts/:ueContextId/assign-ebi",
			HTTPEBIAssignment,
		},
		{
			"RegistrationStatusUpdate",
			http.MethodPost,
			"/ue-contexts/:ueContextId/transfer-update",
			HTTPRegistrationStatusUpdate,
		},
		{
			"ReleaseUEContext",
			http.MethodPost,
			"/ue-contexts/:ueContextId/release",
			HTTPReleaseUEContext,
		},
		{
			"RelocateUEContext",
			http.MethodPost,
			"/ue-contexts/:ueContextId/relocate",
			HTTPRelocateUEContext,
		},
		{
			"UEContextTransfer",
			http.MethodPost,
			"/ue-contexts/:ueContextId/transfer",
			HTTPUEContextTransfer,
		},
		{
			"N1N2MessageUnSubscribe",
			http.MethodDelete,
			"/ue-contexts/:ueContextId/n1-n2-messages/subscriptions/:subscriptionId",
			HTTPN1N2MessageUnSubscribe,
		},
		{
			"N1N2MessageTransfer",
			http.MethodPost,
			"/ue-contexts/:ueContextId/n1-n2-messages",
			HTTPN1N2MessageTransfer,
		},
		{
			"N1N2MessageSubscribe",
			http.MethodPost,
			"/ue-contexts/:ueContextId/n1-n2-messages/subscriptions",
			HTTPN1N2MessageSubscribe,
		},
		{
			"NonUeN2InfoUnSubscribe",
			http.MethodDelete,
			"/non-ue-n2-messages/subscriptions/:n2NotifySubscriptionId",
			HTTPNonUeN2InfoUnSubscribe,
		},
		{
			"NonUeN2MessageTransfer",
			http.MethodPost,
			"/non-ue-n2-messages/transfer",
			HTTPNonUeN2MessageTransfer,
		},
		{
			"NonUeN2InfoSubscribe",
			http.MethodPost,
			"/non-ue-n2-messages/subscriptions",
			HTTPNonUeN2InfoSubscribe,
		},
		{
			"AMFStatusChangeSubscribe",
			http.MethodPost,
			"/subscriptions",
			HTTPAMFStatusChangeSubscribe,
		},
		{
			"AmfStatusChangeNotify",
			http.MethodPost,
			"/:$request.body#/amfStatusUri",
			HTTPAmfStatusChangeNotify,
		},
		{
			"N2InfoNotifyHandoverComplete",
			http.MethodPost,
			"/:$request.body#/n2NotifyUri",
			HTTPN2InfoNotifyHandoverComplete,
		},
		{
			"N1N2TransferFailureNotification",
			http.MethodPost,
			"/:$request.body#/n1n2FailureTxfNotifURI",
			HTTPN1N2TransferFailureNotification,
		},
		{
			"N1MessageNotify",
			http.MethodPost,
			"/:$request.body#/n1NotifyCallbackUri",
			HTTPN1MessageNotify,
		},
		{
			"N2InfoNotify",
			http.MethodPost,
			"/:$request.body#/n2NotifyCallbackUri",
			HTTPN2InfoNotify,
		},
		{
			"NonUeN2InfoNotify",
			http.MethodPost,
			"/:$request.body#/n2NotifyCallbackUri",
			HTTPNonUeN2InfoNotify,
		},
		{
			"AmfStatusChangeNotifyOnSubscriptionUpdate",
			http.MethodPost,
			"/:$request.body#/amfStatusUri",
			HTTPAmfStatusChangeNotifyOnSubscriptionUpdate,
		},
	}
}
